import { ALTERNATIVE_CURRENCIES } from 'constants';

export const CHANGE_ALTERNATIVE_CURRENCY = 'CHANGE_ALTERNATIVE_CURRENCY';
export const INVALIDATE_ALTERNATIVE_CURRENCY_RATE = 'INVALIDATE_ALTERNATIVE_CURRENCY_RATE';

export const ALTERNATIVE_CURRENCY_RATE_REQUEST = 'ALTERNATIVE_CURRENCY_RATE_REQUEST';
export const ALTERNATIVE_CURRENCY_RATE_SUCCESS = 'ALTERNATIVE_CURRENCY_RATE_SUCCESS';
export const ALTERNATIVE_CURRENCY_RATE_FAILURE = 'ALTERNATIVE_CURRENCY_RATE_FAILURE';

const usdCurrency = ALTERNATIVE_CURRENCIES.find(({ code }) => code === 'USD');
export const DEFAULT_ALTERNATIVE_CURRENCY = {
  ...usdCurrency,
  didInvalidate: true,
  isFetching: false,
};

export const ALTERNATIVE_CURRENCY_RATE_LIFESPAN = 30000;
