export const PROFILE_STATES = {
  UNKNOWN: 'UNKNOWN',
  REQUEST_RECEIVED: 'REQUEST_RECEIVED',
  REQUEST_SENT: 'REQUEST_SENT',
  CONTACT: 'CONTACT',
};

export const PROFILE_STATE_PRIORITY = {
  [PROFILE_STATES.UNKNOWN]: 0,
  [PROFILE_STATES.REQUEST_RECEIVED]: 1,
  [PROFILE_STATES.REQUEST_SENT]: 1,
  [PROFILE_STATES.CONTACT]: 2,
};
