/**
 * Copyright (c) 2014-present, Dash Core Group, Inc.
 *
 * @flow
 */

export const MAKE_PAYMENT_TRANSACTION_REQUEST =
  'MAKE_PAYMENT_TRANSACTION_REQUEST';
export const MAKE_PAYMENT_TRANSACTION_SUCCESS =
  'MAKE_PAYMENT_TRANSACTION_SUCCESS';
export const MAKE_PAYMENT_TRANSACTION_FAILURE =
  'MAKE_PAYMENT_TRANSACTION_FAILURE';

export const GET_TRANSACTIONS_REQUEST = 'GET_TRANSACTIONS_REQUEST';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAILURE = 'GET_TRANSACTIONS_FAILURE';

export const BROADCAST_TX_FAILURE = 'BROADCAST_TX_FAILURE';
export const BROADCAST_TX_REQUEST = 'BROADCAST_TX_REQUEST';
export const BROADCAST_TX_SUCCESS = 'BROADCAST_TX_SUCCESS';

export const CREATE_TX_FAILURE = 'CREATE_TX_FAILURE';
export const CREATE_TX_REQUEST = 'CREATE_TX_REQUEST';
export const CREATE_TX_SUCCESS = 'CREATE_TX_SUCCESS';

export const TRANSACTION_RECIPIENT_SCANNED = 'TRANSACTION_RECIPIENT_SCANNED';

export const CREATE_PAYMENT_TRANSACTION_REQUEST =
  'CREATE_PAYMENT_TRANSACTION_REQUEST';
export const CREATE_PAYMENT_TRANSACTION_SUCCESS =
  'CREATE_PAYMENT_TRANSACTION_SUCCESS';
export const CREATE_PAYMENT_TRANSACTION_FAILURE =
  'CREATE_PAYMENT_TRANSACTION_FAILURE';
